---
# tasks file for web

- name: Install Required Package
  package:
    name: python3
    state: present
  become: true
- name: Install Apache Server
  package: 
    name: [ "httpd", "php" ] 
    state: present
  become: true
- name: copy my webpage
  template:
    src: "index.php"
    dest: "/var/www/html"
  become: true
- name: Start Apache Service
  service: 
    name: httpd 
    state: started
  become: true

